rm(list = ls())
graphics.off()

library(dplyr)
library(ggplot2)

setwd("/home/famendezrios/Documents/These/VSCODE-R/HydroBayes/HydroBayes_git/data/data-raw/Synthetic_case/Rhone/rectangular_geometry")

load("values_width_dz.RData")
load("ST_read_XYZ_AIN.RData")
load("ST_read_headersAIN.RData")

AIN_headers <- lapply(all_header_info, as.numeric)
AIN_XYZ <- all_xyz_df

load("ST_read_XYZ_Rhone.RData")
load("ST_read_headersRhone.RData")

RHONE_headers <- lapply(all_header_info, as.numeric)
RHONE_XYZ <- all_xyz_df

geom_RHONE <- results_geom_rect$Rhone
# Modification to the median values (10%) (Rhône)
factor_amplification_Rhone <- 1.1
geom_RHONE$width$median_width <- round(geom_RHONE$width$median_width * factor_amplification_Rhone, digits = 3)
geom_RHONE$riverbed$median_dz <- round(geom_RHONE$riverbed$median_dz * factor_amplification_Rhone, digits = 3)


# Modification to the median values (10%) (Ain)
factor_amplification_Ain <- 1.10
geom_AIN <- results_geom_rect$AIN
geom_AIN$width$median_width <- round(geom_AIN$width$median_width * factor_amplification_Ain, digits = 3)
geom_AIN$riverbed$median_dz <- round(geom_AIN$riverbed$median_dz * factor_amplification_Ain, digits = 3)


dz_rhone <- geom_RHONE$riverbed$median_dz[1] - geom_RHONE$riverbed$median_dz[2]
# Rhone
points <- c(
    26750,
    55900
)

Cross_sections_boundary <-
    list(
        list(
            kp = points[1],
            xyz = data.frame(
                x = rep(points[1], 8),
                y = c(
                    geom_RHONE$width$median_width[2], geom_RHONE$width$median_width[2],
                    0, 0,
                    geom_RHONE$width$median_width[3],
                    geom_RHONE$width$median_width[3],
                    geom_RHONE$width$median_width[1],
                    geom_RHONE$width$median_width[1]
                ),
                z = c(dz_rhone + 10, dz_rhone, dz_rhone, 0, 0, dz_rhone, dz_rhone, dz_rhone + 10)
            )
        ),
        So = -geom_RHONE$So
    )

positions_interface <- c(3, 6) # rg and rd

# Function to perform linear interpolation
interpolate_kp <- function(kp_query, positions_interface) {
    # Initialize a matrix to store the interpolated results
    xyz_interpolated <- matrix(nrow = 0, ncol = 4)


    # Loop through each row of the xyz data
    for (i in 1:nrow(Cross_sections_boundary[[1]]$xyz)) {
        x0 <- Cross_sections_boundary[[1]]$xyz$x[i]
        y0 <- Cross_sections_boundary[[1]]$xyz$y[i]
        z0 <- Cross_sections_boundary[[1]]$xyz$z[i]

        slope <- Cross_sections_boundary$So

        # Calculate the interpolated values
        x <- round(kp_query, digits = 3)
        y <- round(y0, digits = 3)
        z <- round(z0 + (x0 - x) * slope, digits = 3)

        # Add the interpolated results to the matrix
        if (i == 1) {
            xyz_interpolated <- rbind(xyz_interpolated, c(x, y, z, ""))
        } else if (i == positions_interface[1]) {
            xyz_interpolated <- rbind(xyz_interpolated, c(x, y, z, "rg"))
        } else if (i == positions_interface[2]) {
            xyz_interpolated <- rbind(xyz_interpolated, c(x, y, z, "rd"))
        } else {
            xyz_interpolated <- rbind(xyz_interpolated, c(x, y, z, ""))
        }
    }
    return(xyz_interpolated)
}
points_cross_sections <- sort(c(
    points, 34500
))
results <- lapply(points_cross_sections, interpolate_kp, positions_interface = positions_interface)

# Créer un data frame vide pour stocker les résultats
formatted_data <- data.frame(
    V1 = integer(),
    V2 = integer(),
    V3 = integer(),
    V4 = numeric(),
    V5 = numeric(),
    V6 = character()
)

# Remplir le data frame avec les données formatées
for (i in seq_along(points_cross_sections)) {
    new_row <- data.frame(
        V1 = 1,
        V2 = 0,
        V3 = 0,
        V4 = 8,
        V5 = points_cross_sections[i],
        V6 = sprintf("p%03d", i)
    )
    formatted_data <- rbind(formatted_data, new_row)
}


# File path for output
file_path <- "/home/famendezrios/Documents/These/VSCODE-R/HydroBayes/HydroBayes_git/data/data-raw/Synthetic_case/Rhone/PamHYR_synthetic/ST_created/Rhone_basic.ST"

# Open the file for writing
file_conn <- file(file_path, open = "wt")

# Write the header
writeLines("# This file is generated by PAMHYR, please don't modify", file_conn)

# Write formatted data
for (i in 1:nrow(formatted_data)) {
    # Write formatted_data line
    writeLines(
        sprintf(
            "%6d%6d%6d%6d%13.6f  %-20s",
            formatted_data[i, "V1"],
            formatted_data[i, "V2"],
            formatted_data[i, "V3"],
            formatted_data[i, "V4"],
            formatted_data[i, "V5"],
            formatted_data[i, "V6"]
        ),
        file_conn
    )

    # Write results matrix
    if (i <= length(results) && nrow(results[[i]]) > 0) {
        for (j in 1:nrow(results[[i]])) {
            # Initialize a character vector to build the line
            line_parts <- character(0)

            # Format each element according to its type
            for (k in 1:min(4, ncol(results[[i]]))) {
                if (is.numeric(results[[i]][j, k])) {
                    line_parts <- c(line_parts, sprintf("%12.4f", results[[i]][j, k]))
                } else {
                    line_parts <- c(line_parts, sprintf("%12s", results[[i]][j, k]))
                }
            }

            # Combine the parts into a single line
            line <- paste(line_parts, collapse = " ")
            writeLines(line, file_conn)
        }
    }

    # Add a separator line
    writeLines(sprintf("%12.3f%12.3f%12.3f", 999.999, 999.999, 999.999), file_conn)
}

# Close the file
close(file_conn)




ST <- readLines(file_path)

# ST <- c(ST1, ST2)

# Skip the header (starts with '#')
lines <- ST[!grepl("^#", ST)] # remove comment lines

# Split each line by whitespace
split_lines <- strsplit(lines, "\\s+")
# Filter: keep lines with 3–4 elements and no 999.9990
split_lines <- Filter(function(x) {
    length(x) <= 5 && !any(x == "999.9990")
}, split_lines)
# Pad shorter lines with NAs
maxlen <- max(sapply(split_lines, length))
split_lines <- lapply(split_lines, function(x) {
    length(x) <- maxlen
    x
})

# Convert to data frame
df <- as.data.frame(do.call(rbind, split_lines), stringsAsFactors = FALSE)

# Convert numeric columns where possible
df[] <- lapply(df, type.convert, as.is = TRUE)

if (all(is.na(df$V1))) {
    df <- df[, -which(names(df) == "V1")]
} else {
    stop("something is wrong")
}

# Name columns (you can adjust)
colnames(df) <- c("X", "Y", "Z", "Label")[1:ncol(df)]

head(df)

write.table(df, file = "/home/famendezrios/Documents/These/VSCODE-R/HydroBayes/HydroBayes_git/data/data-raw/Synthetic_case/Rhone/PamHYR_synthetic/ST_created/extraction_XYZ_Rhone.csv", row.names = FALSE, col.names = TRUE, sep = ";")


#######################
# AIN
#######################

dz_ain <- geom_AIN$riverbed$median_dz[1] - geom_AIN$riverbed$median_dz[2]

Z0_Ain <- 3.202
Y0_Ain <- 184


points <- c(
    Y0_Ain,
    Y0_Ain + 41461 - 22333
)
X0 <- 34500
Cross_sections_boundary <-
    list(
        list(
            kp = points[1],
            xyz = data.frame(
                x = c(
                    X0 + geom_AIN$width$median_width[2], X0 + geom_AIN$width$median_width[2],
                    X0, X0,
                    X0 + geom_AIN$width$median_width[3],
                    X0 + geom_AIN$width$median_width[3],
                    X0 + geom_AIN$width$median_width[1],
                    X0 + geom_AIN$width$median_width[1]
                ),
                y = rep(Y0_Ain, 8),
                z = c(
                    dz_ain + Z0_Ain + 10,
                    dz_ain + Z0_Ain, dz_ain + Z0_Ain,
                    Z0_Ain, Z0_Ain,
                    dz_ain + Z0_Ain, dz_ain + Z0_Ain,
                    dz_ain + Z0_Ain + 10
                )
            )
        ),
        So = -geom_AIN$So
    )

positions_interface <- c(3, 6) # rg and rd

# Function to perform linear interpolation
interpolate_kp <- function(kp_query, positions_interface) {
    # Initialize a matrix to store the interpolated results
    xyz_interpolated <- matrix(nrow = 0, ncol = 4)


    # Loop through each row of the xyz data
    for (i in 1:nrow(Cross_sections_boundary[[1]]$xyz)) {
        x0 <- Cross_sections_boundary[[1]]$xyz$x[i]
        y0 <- Cross_sections_boundary[[1]]$xyz$y[i]
        z0 <- Cross_sections_boundary[[1]]$xyz$z[i]

        slope <- Cross_sections_boundary$So

        # Calculate the interpolated values
        x <- round(x0, digits = 3)
        y <- round(kp_query, digits = 3)
        z <- round(z0 + (y0 - y) * slope, digits = 3)

        # Add the interpolated results to the matrix
        if (i == 1) {
            xyz_interpolated <- rbind(xyz_interpolated, c(x, y, z, ""))
        } else if (i == positions_interface[1]) {
            xyz_interpolated <- rbind(xyz_interpolated, c(x, y, z, "rg"))
        } else if (i == positions_interface[2]) {
            xyz_interpolated <- rbind(xyz_interpolated, c(x, y, z, "rd"))
        } else {
            xyz_interpolated <- rbind(xyz_interpolated, c(x, y, z, ""))
        }
    }
    return(xyz_interpolated)
}
points_cross_sections <- sort(c(
    points
))
results <- lapply(points_cross_sections, interpolate_kp, positions_interface = positions_interface)

# Créer un data frame vide pour stocker les résultats
formatted_data <- data.frame(
    V1 = integer(),
    V2 = integer(),
    V3 = integer(),
    V4 = numeric(),
    V5 = numeric(),
    V6 = character()
)

# Remplir le data frame avec les données formatées
for (i in seq_along(points_cross_sections)) {
    new_row <- data.frame(
        V1 = 1,
        V2 = 0,
        V3 = 0,
        V4 = 8,
        V5 = points_cross_sections[i],
        V6 = sprintf("p%03d", i)
    )
    formatted_data <- rbind(formatted_data, new_row)
}


# File path for output
file_path <- "/home/famendezrios/Documents/These/VSCODE-R/HydroBayes/HydroBayes_git/data/data-raw/Synthetic_case/Rhone/PamHYR_synthetic/ST_created/AIN_basic.ST"

# Open the file for writing
file_conn <- file(file_path, open = "wt")

# Write the header
writeLines("# This file is generated by PAMHYR, please don't modify", file_conn)

# Write formatted data
for (i in 1:nrow(formatted_data)) {
    # Write formatted_data line
    writeLines(
        sprintf(
            "%6d%6d%6d%6d%13.6f  %-20s",
            formatted_data[i, "V1"],
            formatted_data[i, "V2"],
            formatted_data[i, "V3"],
            formatted_data[i, "V4"],
            formatted_data[i, "V5"],
            formatted_data[i, "V6"]
        ),
        file_conn
    )

    # Write results matrix
    if (i <= length(results) && nrow(results[[i]]) > 0) {
        for (j in 1:nrow(results[[i]])) {
            # Initialize a character vector to build the line
            line_parts <- character(0)

            # Format each element according to its type
            for (k in 1:min(4, ncol(results[[i]]))) {
                if (is.numeric(results[[i]][j, k])) {
                    line_parts <- c(line_parts, sprintf("%12.4f", results[[i]][j, k]))
                } else {
                    line_parts <- c(line_parts, sprintf("%12s", results[[i]][j, k]))
                }
            }

            # Combine the parts into a single line
            line <- paste(line_parts, collapse = " ")
            writeLines(line, file_conn)
        }
    }

    # Add a separator line
    writeLines(sprintf("%12.3f%12.3f%12.3f", 999.999, 999.999, 999.999), file_conn)
}

# Close the file
close(file_conn)



ST <- readLines(file_path)

# ST <- c(ST1, ST2)

# Skip the header (starts with '#')
lines <- ST[!grepl("^#", ST)] # remove comment lines

# Split each line by whitespace
split_lines <- strsplit(trimws(lines), "\\s+")
# Filter: keep lines with 3–4 elements and no 999.9990
split_lines <- Filter(function(x) {
    length(x) <= 5 && !any(x == "999.9990")
}, split_lines)
# Pad shorter lines with NAs
maxlen <- max(sapply(split_lines, length))
split_lines <- lapply(split_lines, function(x) {
    length(x) <- maxlen
    x
})

# Convert to data frame
df <- as.data.frame(do.call(rbind, split_lines), stringsAsFactors = FALSE)

# Convert numeric columns where possible
df[] <- lapply(df, type.convert, as.is = TRUE)

# Name columns (you can adjust)
colnames(df) <- c("X", "Y", "Z", "Label")[1:ncol(df)]

head(df)

write.table(df, file = "/home/famendezrios/Documents/These/VSCODE-R/HydroBayes/HydroBayes_git/data/data-raw/Synthetic_case/Rhone/PamHYR_synthetic/ST_created/extraction_XYZ_AIN.csv", row.names = FALSE, col.names = TRUE, sep = ";")
