last <- function(data) {
    utils::tail(data, n = 1)
}

# Assuming Kflood_SU is your nested list
extract_priors <- function(nested_list) {
    priors <- list()

    # Recursive function to extract 'prior' elements
    extract <- function(x) {
        if (is.list(x)) {
            if ("prior" %in% names(x)) {
                priors <<- c(priors, list(x$prior))
            } else {
                lapply(x, extract)
            }
        }
    }

    # Apply the recursive function
    extract(nested_list)

    # Flatten the list of priors
    flat_priors <- unlist(priors, recursive = FALSE)

    return(flat_priors)
}


get_init_prior <- function(parameter, FIX_dist = FALSE) {
    # Identify if parameter is remnantErrorModel class
    logical_test <- class(parameter[[1]]) == "remnantErrorModel"
    if (logical_test) { # if remnantErrorModel, a list is needed
        init_priors <- list()
    } else { # if not a vector is needed
        init_priors <- numeric(0)
    }

    counter_gamma <- 1
    for (i in parameter) {
        # Handle if parameters is remnantErrorModel
        if (logical_test) {
            param <- i$par
            number_var_error_model <- seq_along(param)

            for (local_counter in number_var_error_model) {
                if (FIX_dist) {
                    init_priors[[counter_gamma]] <- param[[local_counter]]$init
                    counter_gamma <- counter_gamma + 1
                } else {
                    if (param[[local_counter]]$prior$dist != "FIX") {
                        init_priors[[counter_gamma]] <- param[[local_counter]]$init
                        counter_gamma <- counter_gamma + 1
                    }
                }
            }
        } else {
            # Handle if parameters comes from theta
            param <- i
            if (FIX_dist) {
                init_priors <- c(init_priors, param$init)
            } else {
                if (param$prior$dist != "FIX") {
                    init_priors <- c(init_priors, param$init)
                }
            }
        }
    }
    return(init_priors)
}


write_RUGFile <- function(RUG_path,
                          RUGFile_data,
                          RUG_format) {
    # Open a .RUG file for writing
    fileConn <- file(RUG_path, "w")
    # Write the first line as a comment
    writeLines("* This file is generated by PAMHYR, please don't modify", fileConn)
    formatted_lines <- sapply(1:nrow(RUGFile_data), function(i) {
        sprintf(
            RUG_format,
            "K",
            RUGFile_data$id_reach[i],
            RUGFile_data$KP_start[i],
            RUGFile_data$KP_end[i],
            RUGFile_data$Kmin[i],
            RUGFile_data$Kflood[i]
        )
    })

    # Write the formatted lines to the file
    writeLines(formatted_lines, fileConn)


    # Close the file
    close(fileConn)
}

copy_folder <- function(source, destination) {
    # Create the destination directory if it doesn't exist
    if (!dir.exists(destination)) {
        dir.create(destination, recursive = TRUE)
    }

    # List all files and subdirectories in the source
    items <- list.files(source, full.names = TRUE, recursive = FALSE)

    for (item in items) {
        item_relative <- basename(item)
        dest_item <- file.path(destination, item_relative)

        if (dir.exists(item)) {
            # If the item is a subdirectory, recursively copy it
            copy_folder(item, dest_item)
        } else {
            # If the item is a file, copy it
            file.copy(item, dest_item)
        }
    }
}

convert_9999_to_NA <- function(values) {
    values[values == -9999] <- NA
    return(values)
}

read_fortran_data <- function(file_path, col_widths_RUGFile, skip = 0) {
    # Read the file with the fixed-width format
    data <- utils::read.fwf(file_path, widths = col_widths_RUGFile, header = FALSE, skip = skip)
    data <- data[, -3]
    colnames(data) <-
        c(
            "",
            "id_reach",
            "KP_start",
            "KP_end",
            "Kmin",
            "Kflood"
        )
    return(data)
}

get_prior_distribution <- function(K_prior) {
    sapply(K_prior, function(x) x$prior$dist)
}

get_param_vector_MAP_values <- function(SU_Kmin, SU_Kflood, MAP) {
    param_MAP_values <- vector("list", sum(lengths(SU_Kmin)) + sum(lengths(SU_Kflood)))
    names_all <- c(
        unlist(lapply(names(SU_Kmin), function(l1) {
            paste0("Kmin_", l1, "_", names(SU_Kmin[[l1]]))
        })),
        unlist(lapply(names(SU_Kflood), function(l1) {
            paste0("Kflood_", l1, "_", names(SU_Kflood[[l1]]))
        }))
    )
    names(param_MAP_values) <- names_all

    counter <- 1
    MAP_idx <- 1
    SU_Kmin_Kflood <- c(SU_Kmin, SU_Kflood)

    for (id_reach in SU_Kmin_Kflood) { # Browse the id reach (tributary, main channel, etc) in the Kmin and Kflood
        for (id_SU in id_reach) { # Browse the spatial unit (SU) of the id_reach
            # id_SU <- SU_Kmin[[3]][[1]]
            # idea: keep the order of the config model !

            # Get initial values of all parameters
            param_temp <- get_init_prior(extract_priors(id_SU), FIX_dist = TRUE)
            # If prior distribution is FIX, then keep the initial value.
            # Otherwise, modify by the MAP value to calculate residuals
            idx <- which(get_prior_distribution(id_SU$prior) != "FIX")

            # Get the number of distribution different to FIX distribution to move indicator in the MAP variable
            n <- length(idx)

            if (n != 0) {
                param_temp[idx] <- MAP[MAP_idx:(MAP_idx + n - 1)]
            }

            MAP_idx <- MAP_idx + n

            param_MAP_values[[counter]] <- param_temp

            counter <- counter + 1
        }
    }
    return(unlist(param_MAP_values))
}

remnantErrorModel_default <- function(name) {
    RBaM::remnantErrorModel(
        fname = name,
        funk = "Constant",
        par = list(parameter(
            name = "intercept",
            init = 0.01,
            prior.dist = "Exponential",
            prior.par = c(0, 0.01) # 0 is the threshold and 0.01 is the scale
        ))
    )
}


# Set paths

load_experiment <- function(file_main_path, cal_case, path_experiment, all_events) {
    path_input <- file.path(file_main_path, "Experiments_Input_Data", cal_case)

    if (!file.exists(path_input)) {
        stop("Experiment input file does not exist: ", cal_case)
    }

    source(path_input)

    path_polynomial <- file.path(
        path_experiment,
        sub("\\.r$", "", cal_case)
    )

    path_BaM_folder <- file.path(path_polynomial, "BaM")

    path_plot_folder <- file.path(path_BaM_folder, "post_traitement")

    path_RData <- file.path(path_plot_folder, "RData")

    dir.create(path_plot_folder, showWarnings = FALSE)
    dir.create(path_RData, showWarnings = FALSE)

    path_model_HM <- file.path(
        path_polynomial,
        "model_mage"
    )

    path_model_HM_events <- paste0(
        file.path(
            path_model_HM,
            all_events
        ),
        "/"
    )


    return(list(
        path_experiment = path_input,
        path_polynomial = path_polynomial,
        path_BaM_folder = path_BaM_folder,
        path_plot_folder = path_plot_folder,
        path_RData = path_RData,
        path_model_HM_events = path_model_HM_events,
        path_model_HM = path_model_HM
    ))
}
